"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../../Componets/header";
import Footer from "../../Componets/footer";
import { Provider } from "react-redux";
import { store } from "./redux/store";
import { Toaster } from "react-hot-toast";
import AuthContextProvider from "../../context/AuthContext";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          <Toaster position="top-right" />
          <AuthContextProvider>
            <Header />
            {children}
            <Footer />
          </AuthContextProvider>
        </Provider>
      </body>
    </html>
  );
}
